### ISSUE TITLE
An option to disable shoryuken restart on error?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [phstc/shoryuken#109]
Let's take this example

```ruby
class MyWorker
  include Shoryuken::Worker

  def perform(sqs_msg, body)
    send_email(body.to_s)
    sqs_msg.delete
  rescue StandardError => error
    Shoryuken::Logging.logger.error "#{ error }"
    Shoryuken::Logging.logger.error "#{ error.backtrace.join("\n") }"
    abort "Shutdown because of error"
  end

  private

  def send_email(body)
    actually_send_email(body)
    raise "Whatever"
  end

  def actually_send_email(body)
    # code to send an email
  end

end
```

You may think this will send one message and exit.
Wrong, if you launch this process in background (without a PTY), it will send one message, then raise a IO error (due to missing stdout), restart the worker and will keep sending email messages.

Are there any possible way to disable the behavior where Shoryuken restarts when an exception is catched?

Thanks, meanwhile, I'll throw `abort` out of the window

**Comment by phstc** [comment]
Hey @Fire-Dragon-DoL 

It's not a Shoryuken behaviour, it's a SQS behaviour, check the [SQS message life cycle](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/MessageLifecycle.html). Shoryuken tries to be as transparent as possible to SQS.

- Using SQS you must `delete` (read it as `ack` if you are coming from other queueing systems) within the [message visibility timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/AboutVT.html), otherwise the message will become available again
- I always recommend to create [idempotent](https://en.wikipedia.org/wiki/Idempotence) and transactional workers. Check [this](https://github.com/mperham/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional) from Sidekiq :star: 

BTW Shoryuken has an [auto_delete](https://github.com/phstc/shoryuken/wiki/Worker-options#auto_delete) option, in case you want to omit `sqs_msg.delete`. But it's not called when the worker raises an exception.

**Comment by Fire-Dragon-DoL** [comment]
@phstc I'm aware of that, I wasn't concerned about the message not being deleted, I was concerned by shoryuken **restarting** the worker after an uncaught exception leaked up to the top (of `perform` method)

**Comment by phstc** [comment]
Shoryuken isn't restarting the worker, the message gets back to the queue if you don't `delete` then to Shoryuken again. Check the SQS message life cycle.

**Comment by Fire-Dragon-DoL** [comment]
Ok so it's not restarting the worker, it's not shutting down once the exception is leaked. Isn't this bad in any case?

**Comment by gshutler** [comment]
@Fire-Dragon-DoL, are you expecting the raised exception to shut down Shoryuken as a whole?

If so, that won't happen. The instance of the worker class that processes the message will always be discarded whether it succeeds or fails. Every message gets a new instance of the worker class to process it.

However, Shoryuken will recognise the error but spawn a replacement thread to process new messages. Shoryuken will not, and should not, shutdown in the face of a single message failing. If that were the case one unexpected error would stop all messages from being processed which wouldn't be a good thing.
