### ISSUE TITLE
remote killing workers?

### ISSUE THREAD

**Issue by jtoy** [phstc/shoryuken#211]
Is there any recommended way to be able to kill SQS/shoryuken workers?
I have workers that have jobs that can last days and I want to kill them sometimes. 
To write this using shoryuken, I would have to modify my workers to listen on SQS and to listen on a separate channel/socket for messages to shutdown.
It seems like in this kind of situation I might need to just write my own custom worker system instead of using SQS.

**Comment by phstc** [comment]
Hi @jtoy 

Please check #187. There's an interesting thread about it. Any input is welcomed 🍻 

cc/ @mariokostelac

**Comment by mariokostelac** [comment]
Sorry for a very late reply.
I've had discussions with my mates in Intercom and problem is far more difficult than it seems.

Let's say we have actor code that looks like:
```ruby
db_connection = pool.get
time_waster.waste
pool.restore(db_connection)
```

If we kill the process any time after line 1 is executed and before line 3 is finished, we end in very broken state where we haven't returned shared resource to the shared pool. General problem here is actually sharing the state between two different subjects. The only correct solution here is to kill the process actually. Of course, if you do not design your services (you should) to support non-graceful shutdowns, that solution will break for you.

The way how we solved that is that we introduced a middleware that kills the process and we have process manager to bring the process up. I do not feel that it should be part of shoryuken because killing the process could cause troubles for people, but we should add an example to wiki how to make one and what are requirements for that solution.

**Comment by mariokostelac** [comment]
Also, I do not feel that remote killing should be part of the gem itself. That feature could introduce a huge lot of new problems and complexity with a very questionable benefit.
If you feel I am wrong, feel free to reopen, I am happy to change my mind :).

**Comment by jtoy** [comment]
I agree, but I think some solution should be written about.

-- Sent from my mobile

**Comment by mariokostelac** [comment]
@jtoy what are situations when you want to kill those workers?

**Comment by jtoy** [comment]
all my workers are long term jobs, lasting hours to weeks.  I did add a simple kill switch.  I have the worker start another thread and checks every minute for a status update from the server. The server can tell the worker to shut down in that checkin period.

**Comment by mariokostelac** [comment]
@jtoy you can take a look at https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/auto_extend_visibility.rb to get an idea for implementation :).
