### ISSUE TITLE
Running multiple instances of shoryuken

### ISSUE THREAD

**Issue by eyalrosen** [phstc/shoryuken#232]
Hi Everyone!
First of all, just started playing with shoryuken and I LOVE IT. You're truly awesome :)
Second, I wanted to know of I could have multiple servers running shoryuken and it would make sure that each message would be processed only once.
Thanks!

**Comment by phstc** [comment]
Hey @eyalrosen 

> First of all, just started playing with shoryuken and I LOVE IT. You're truly awesome :)

❤️ 🍻 

That's correct, each message should be proceed once. But you need to make sure to delete the messages once you finish processing them and to do not exceed the `visibility_timeout`, otherwise AWS SQS will make them available again.

This controlled by AWS SQS, not by Shoryuken.

Have a look at [Message Lifecycle](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/MessageLifecycle.html) for more details.

**Comment by eyalrosen** [comment]
Thanks! :)

**Comment by kamok** [comment]
@phstc 
Can you illustrate what happens in this scenario?
Imagine 2 instances of shoryuken, A and B. A receives a message meant for B. It does not process it or delete it. The message is now set to be timed out, and not visible. When the message is available again (30 seconds default), can you ensure that B gets the message? I feel like there's a chance that A grabs it again and the message is stuck in limbo.

**Comment by phstc** [comment]
@kamok I don't know your use case, but it does not seem to be a good practice. If you want A and B to process specific messages, I would use specific queues, a queue for A and a queue for B. Otherwise, A can continuously receive messages for B.
