### ISSUE TITLE
delayed extensions

### ISSUE THREAD

**Issue by anazar** [phstc/shoryuken#238]
In researching shoryuken as an alternative to sidekiq I don't see any way to use delayed extensions.  

See: https://github.com/mperham/sidekiq/wiki/Delayed-extensions

Any consideration on adding support for this or any thoughts on how to do this currently?

**Comment by phstc** [comment]
Hey @anazar 

That seems to be an interesting. No one else asked for it yet, so it isn't in the roadmap. How do you use it? For mailers, active record?

The biggest difference on that comparing with Sidekiq, is because of SQS itself, [the maximum we can delay is 15 minutes](https://github.com/phstc/shoryuken/blob/bf65b6e90bd6648279c89eeaafeb3f21cbbfd1c1/lib/shoryuken/extensions/active_job_adapter.rb#L44)

**Comment by anazar** [comment]
@phstc i actually prefer being able to give my worker methods names vs having to use perform.  So i don't actually use it to specifically delay for a period of time.  I just use it to trigger async on a method. 

ie. MyWorker.delay.do_specific_task

**Comment by phstc** [comment]
@anazar I see, that seems handy. But checking how Sidekiq does that, and how it has to disable it to avoid conflicts with other gems. I don't think it's worth adding, I mean, for simplicity purposes.

I know it's far from ideal, if you don't use to call `perform_async`:

```ruby
alias_method :perform_async, :do_specific_task
```

Anyway, I kind of like having `perform_async`, it enforces the SRP.
