### ISSUE TITLE
ExponentialBackoffRetry not being used when an active worker is shut down

### ISSUE THREAD

**Issue by eni9889** [phstc/shoryuken#255]
Hi,

I am using phantomjs and poltergeist with shoryuken and run into memory issues so have to periodically restart the shoryuken process. The issue is that the retry-intervals do not get used when I shutdown the shoryken process. Is there a way to force an exception in the running process so that the retry interval will be used? Thanks for the help!

**Comment by phstc** [comment]
Hi @eni9889 

[Hard restart raises `Shutdown`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L235), which is not rescued [here](https://github.com/phstc/shoryuken/blob/ad4f1c3840eb3fe4e8d5f2d70a448a670722f87f/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L10). You can extend the `ExponentialBackoffRetry` to rescue it, which does not feel like a good thing to do, or in the beginning of your worker do something like [this](https://github.com/phstc/shoryuken/blob/ad4f1c3840eb3fe4e8d5f2d70a448a670722f87f/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L41), so in case a hard shutdown happens, your message won't get back to the queue before the visibility timeout set. WDYT?

**Comment by eni9889** [comment]
@phstc those are great suggestions I think I'll try the last one and see how it goes and let you know. Thanks for the tip!

**Comment by phstc** [comment]
@eni9889 could you give more details on your implementation. Because of the nature of SQS, after a hard shutdown the message will be back to the queue, as the processor won't be able to delete then. So you use case you don't want them to be available again in that way, you want to wait longer to process them, something like that?

`ExponentialBackoffRetry` is meant to be used for other kind of exceptions, not for hard shutdown.
