### ISSUE TITLE
How to configure not to retry a message

### ISSUE THREAD

**Issue by fcastellanos** [phstc/shoryuken#264]
Hi, this is more of a question, how can I configure Shoryuken or SQS to not retry messages?

**Comment by phstc** [comment]
Hi @fcastellanos 

Shoryuken and SQS don't auto retry messages. What happens in SQS is if you don't delete your messages after consuming them, once the their visibility timeout expires, SQS will make them available again.

How to prevent that:

- Delete messages after their consumption 
- Configure a [dead letter queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html), so if a message gets consumed (in flight) and does not get delete, SQS will auto move it to a DL queue instead of making it available again
