### ISSUE TITLE
Document new polling strategies 

### ISSUE THREAD

**Issue by phstc** [phstc/shoryuken#294]
We should document (Wiki) the new polling strategies

**Comment by phstc** [comment]
Done https://github.com/phstc/shoryuken/wiki/Polling-strategies

**Comment by kamok** [comment]
@phstc I was a bit confused on the documentation on WWR, can you clarify a bit? `WeightedRoundRobin`.

Here's my take on what's happening according to what you wrote:

queue 1 - max weight: 8
queue 2 - max weight: 4
queue 3 - max weight: 1

A queue weight starts at 1, and after every fetch returning messages, it gets increased one-by-one until it reaches the max weight. In this example, the max weight for queue1 is 8.
Supposing all queues are full of messages, how it would look like:

Step 1: fetches messages from queue1 - `q1: 1, q2: 2, q3: 1` 
Step 2: fetches messages from queue2 - `q1: 2, q2: 1, q3: 1`
Step 3: fetches messages from queue3 - `q1: 2, q2: 1, q3: 1` ??? Why was queue 3 fetched when queue 1 should've been at weight 2? 

On Step 1, queue1 was fetched, so the other 2 queues add 1 if they were not max max weight. queue2 went from 1 to 2, and queue 3 stays at 1 (its max)

On Step 2, queue2 was fetched (since it is the highest priority at that moment in time). Queue3 stays at 1, and queue 1 is increased to priority 2 since it wasn't fetched nor was at max

On Step 3, ???

**Comment by phstc** [comment]
> 1. fetches messages from `queue1`
> 2. fetches messages from `queue2`
> 3. fetches messages from `queue3`
> 4. fetches messages from `queue1`
> 5. fetches messages from `queue1`
> 6. fetches messages from `queue2`
> 7. fetches messages from `queue2`
> 8. fetches messages from `queue3`

https://github.com/phstc/shoryuken/wiki/Polling-strategies

@kamok a queue weight only increases one by one, and only when it gets fetched. Se the example above

**Comment by phstc** [comment]
BTW `queues` is an array, and [the queues are added at the end of it](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/polling/weighted_round_robin.rb#L29). The order is not respected precisely (only `q1` then `q2` ...), what's respected is the number of fetches that's going to be done on a queue based on its weight. 

Does that make sense?
