### ISSUE TITLE
Readme/wiki should have cost calculation example

### ISSUE THREAD

**Issue by clemens** [phstc/shoryuken#304]
Hi there,

first of all: I like this gem – it's comparatively easy to get started if you're used to Sidekiq. Kudos to you.

As for my issue: I was surprised to see almost $40 on last month's AWS bill and seeing almost $20 on the current status for January since I'm not even using the feature which uses Shoryuken in production yet. Since the rollout will happen quite soon, I wanted to investigate a bit and found out that my test environment issued almost 100 million requests (!) last month. I was wondering where this was coming from but couldn't find any cost calculation examples in your readme/wiki – which is quite unfortunate.

I'm happy to provide a pull request and fix this, however, I'd like to make sure that I'm understand correctly how everything works. So maybe you could verify the following example?

Here's a bit of context: I have two servers, one actual app server and one doing video conversion. The app server uploads videos to S3 and the bucket is configured to put notifications directly into SQS which the video conversion server then picks up (via Shoryuken), processes the videos and puts them back into S3, which again puts notifications into SQS and the app server picks them up (again using Shoryuken).

The current Shoryuken configs are as follows:

- The video conversion service instance for development (for when I'm testing on my localhost) and staging are each set to `concurrency: 5` and `delay: 0`.
- The worker on the app server in the staging environment has no settings, so I assume the defaults are used (`concurrency: 25` and `delay: 0`). The worker on my localhost can be neglected since I'm only starting it every now and again when I'm actively testing stuff.

So I assume this results in the following calculation:

- There are 35 workers (2 x concurrency 5 + 1 x concurrency 25).
- Each worker sends a request to SQS every second, resulting in 35 requests per second.
- 35 requests per second x 86,400 seconds per day = 3,024,000 requests per day => ~ 90-95 million requests per month
- First million requests is free, then it's 40 cents per million requests => $35-40 per month (like I had in December).

Is this correct? Because if yes, the entry in the wiki ("First 1 million Amazon SQS Requests per month are free (see SQS pricing), so even with a host checking for new messages every second you will stay in the free tier.") is misleading because in the default setup, Shoryuken sends 25 messages per second, not 1, resulting in over 2 million requests per day (so already beyond the free tier).

Looking forward to hearing from you.

**Comment by phstc** [comment]
Hey @clemens

🍺 

> is misleading because in the default setup

I'm sorry to hear that, it was not the intention. I'm not sure in which wiki page you found that, but I changed [this one](https://github.com/phstc/shoryuken/wiki/Shoryuken-options) to encourage people to check that in AWS SQS directly. I agree, that affirmation isn't guaranteed to be true depending on your setup and queue load.

It's kind of hard to calculate how much it would cost.

```yaml
concurrency: 25 # number of available processors
delay: 0
```

That means that, Shoryuken will have a single fetcher trying to poll messages from your queues, whenever a processor is available. As you are using `delay: 0`, this also causes Shoryuken to continuous check queues whenever a processor is available. Setting it to something higher than `0`, will pause empty queue.

When you start Shoryuken, it will have 25 processors available, so the fetcher will perform 3 requests to SQS (it supports up to 10 messages per request only).

- fetch 10
- assign to processors
- fetch more 10
- assign to processors
- fetch more 5
- assign to processors

Even if the queue being polled is full of messages, it does not mean that SQS will give you 10 messages per request, when you ask for 10, it's not guarantee it will give you 10, so it's hard to count the exact number of requests.

While doing that (multi threaded), if a processor finishes processing, fetcher will try to fetch a message for it. But it does not mean that it will be always 1x1, when the fetcher gets triggered, there may be more than one processor available, consequently polling more than one message. 

Unless you use batchable workers, each message will result in another request to SQS in order to be deleted. If you use auto extended visibility timeout, this also may cause more requests to SQS.

> I'm happy to provide a pull request and fix this

Please! I'm very opened for any change that can help people to make the best use of it.

Did that help?

**Comment by truongnmt** [comment]
```
concurrency: 25 # number of available processors
delay: 0
```

> When you start Shoryuken, it will have 25 processors available, so the fetcher will perform 3 requests to SQS (it supports up to 10 messages per request only).

This is very important information! Wished it's added to the README. I though all processors will poll the queue. The same with OP's thought!

> Each worker sends a request to SQS every second, resulting in 35 requests per second.
35 requests per second x 86,400 seconds per day = 3,024,000 requests per day => ~ 90-95 million requests per month

So if OP has 35 workers, it will be 4 reqs/s.
Assuming the queues is empty for the whole month, it will be:
4 reqs per second x 86,400 seconds per day = 10,368,000 request per month

Which according to [AWS Price calculator](https://calculator.aws/#/createCalculator) it will be roughly 4$!

So he did get the bill for 40$, the remain 38$ must be to interact with the queue (delete message request as you said).

---

> Each message will result in another request to SQS in order to be deleted.

I would like to confirm this as well. Does this still true?

For example, I enqueue 1000 requests and after workers finish with all that request, it will need another 1000 requests to delete those messages right. Assuming that use no batch workers and have no other request to SQS.

---

https://github.com/phstc/shoryuken/wiki/Shoryuken-options#cache_visibility_timeout

> By default, Shoryuken will make requests against SQS for getting the updated queue visibility timeout, so if you change the visibility timeout in SQS, Shoryuken will automatically update it.

I would like to ask how often does Shoryuken checking for this value? Can you show me the code too? Thanks a lot!!! @phstc 🥇
