### ISSUE TITLE
Single-threaded Job Request

### ISSUE THREAD

**Issue by waynerobinson** [phstc/shoryuken#333]
Am I right in thinking that the job request task is single-threaded?

https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L21-L23

We've noticed some issues where the job request loop can't keep up with the messages being processed, even when we request up to 10 at a time. 

Would there be a way to potentially put these in a pool of configurable size? The only other solution that we seem to have right now is to run multiple Shoryuken workers (which is fine too for our current workload).

P.S. Good work on the implementation of concurrent-ruby by the way! 👍

**Comment by phstc** [comment]
hi @waynerobinson 

Thanks a lot for testing out v3.

It's kind of single threaded, but it executes every 0.1 seconds.  On my tests, I've also added a `dispatch` call in [here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L56), but it didn't help much with the performance. As [this](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L63), ensures one fetch at time.

I guess we can remove the `@dispatching` checker, but we would need to control the number of ready processors in a different way, because `remaining_capacity` will only get updated once we assign the processors.  

WDYT? I can def play with it.

**Comment by waynerobinson** [comment]
I'll have a look at a couple of different options at our end too. I do kind of think that just having a pool of workers requesting messages concurrently and dispatching them would be fine (at least in our use case). 

Each of the dispatchers in the pool would check to see if there is a free worker before firing, just as it does now. 

The worst case scenario is that > 1 dispatcher sees that there is enough workers and requests messages at the same time, but that just means that they're held in their own queue for the time it takes to clear out enough workers to deliver messages to them. 

The primary reason you'd enable a dispatcher pool is because your workers execute very quickly anyway, so I don't think this would cause too much problem regarding holding messages locally for a short time before they get sent to a worker.

**Comment by phstc** [comment]
> The worst case scenario is that > 1 dispatcher sees that there is enough workers and requests messages at the same time, but that just means that they're held in their own queue for the time it takes to clear out enough workers to deliver messages to them.

The issue if that is because the time they held messages, would count against the message visibility timeout, it may cause messages getting into DL queues.

> The primary reason you'd enable a dispatcher pool is because your workers execute very quickly anyway, so I don't think this would cause too much problem regarding holding messages locally for a short time before they get sent to a worker.

I agree, but for a generic solution, we can't rely that all workers will process fast. 

I think, if I can figure out how to proper check `remaining_capacity`, like with a counter, we can just remove the checker `@dispatching`, I didn't do it before, because I couldn't figure out how to make `Concurrent::FixedThreadPool` tell me when a thread dies. 

@mariokostelac gave a great solution to have a fetcher per processor, so once a processor finishes, it fetches a new message for itself, all in parallel, with any other available processor. I think it's a beautiful solution, but... it would drastically increase the number of SQS requests, which can be really bad money-wise for some users.

**Comment by waynerobinson** [comment]
I don't think the message visibility is an issue because the reason you'd have a larger pool is because the processors are faster than your IO to AWS/SQS. 

A fetcher per processor has its own problems because you lose the ability to do batch-based requests. If this is the default and your workers *are* actually slow, then you have up to 9 messages that are processed before you'd get to the 10th and you'd have a real message visibility issue.

And that's not really a cost problem for us, it's a round-trip IO issue of doing a request per message where we don't have to.

With a pool of dispatchers, at least you get some control over how you want to deal with this issue.

**Comment by phstc** [comment]
> I don't think the message visibility is an issue because the reason you'd have a larger pool is because the processors are faster than your IO to AWS/SQS.

It's hard to affirm that for sure, people do crazy stuff, they can configure crazy stuff. 

> A fetcher per processor has its own problems because you lose the ability to do batch-based requests. If this is the default and your workers are actually slow, then you have up to 9 messages that are processed before you'd get to the 10th and you'd have a real message visibility issue.

How this would be a visibility issue? If I have 9 available processors, and each of them request a single message, there will be 9 requests and 9 messages retrieved, the 10th message will be waiting in SQS for the next available processor. But I also do agree, it isn't a silver bullet solution, too many requests. In case of fast processors, it's most likely they would spend more time requesting messages than processing them.

> With a pool of dispatchers, at least you get some control over how you want to deal with this issue.

I need to think more about it. 

But I still think if we can control when a processor dies, we can just call `dispatch`, whenever a processor is done or dies. Pretty similar to the previous solution.

**Comment by waynerobinson** [comment]
They don't request a single message though. They request a batch of 10 messages to cut down on IO roundtrip.

**Comment by phstc** [comment]
@waynerobinson how long are you jobs taking to process, what do you have configured for concurrency? 

In theory the heartbeat should be every 0.1 seconds.

**Comment by waynerobinson** [comment]
But from what I can see, doesn't it let only one dispatcher run at a time.

Admittedly, my experience regarding processing speed was based on 2.x, not 3.x. But that code looked like the dispatcher only runs synchronously.

If not, feel free to close this issue and thanks for solving an annoying problem. :)

**Comment by phstc** [comment]
> Admittedly, my experience regarding processing speed was based on 2.x, not 3.x. But that code looked like the dispatcher only runs synchronously.

Thanks for letting me know that 🍻 In 3.x the fetcher should happen every 0.1 seconds, in separate thread, so no matter if the workers are busy or not, a fetch should happen every 0.1. But indeed, it's one fetch at time. I'm playing around in #336 to try to fetch more at once, like if there's a more than 10 available processors, let's say 15, fetch 10 and 5 in parallel, instead of fetching 10, waiting for 0.1 seconds, then fetch 5 (or more, if any processor became available).

**Comment by phstc** [comment]
Just to recap:

1. yup. Shoryuken does one request at time, and it can be up to 10 messages at time, even if there are more than 10 available processors. 
2. I think one possible solution/improvement would be to have a  fetcher for every 10 processors, and these fetchers could fetch in "parallel"

I will try to play around with that idea.

**Comment by waynerobinson** [comment]
I wonder if that actually solves the right portions of this problem. I don't even think we need a dispatcher per 10 processors.

Just a configurable quantity would be fine. 

Since the move to the pool-based dispatch loop, you could just modify this to have `dispatch_async` post as many times as there are empty threads in the pool (or just always post `thread_size` times as the pool is set to discard any excess messages).

**Comment by phstc** [comment]
@waynerobinson solved in 3.1.0 🍻 You can create a group per queue for having concurrent fetchers 🎉 

https://github.com/phstc/shoryuken/wiki/Processing-Groups
