### ISSUE TITLE
Extra Boot Config

### ISSUE THREAD

**Issue by waynerobinson** [phstc/shoryuken#334]
Where is the best place to put extra boot config these days:

```ruby
Shoryuken.configure_server do |config|
  config.aws = {
    secret_access_key:  ENV["AWS_SECRET_ACCESS_KEY"],
    access_key_id:      ENV["AWS_ACCESS_KEY_ID"],
    region:             ENV["AWS_REGION"],
    receive_message:    {
      wait_time_seconds: RUBY_ENV == "production" ? nil : 5,
      attribute_names: %w(
        ApproximateReceiveCount
        SentTimestamp
      )
    }
  }
end
```

I understand we can just remove the specific ENV references now, but where do we put the `receive_message` config?

**Comment by waynerobinson** [comment]
Do I just set it directly on `Shoryuken` with:

```ruby
Shoryuken.sqs_client_receive_message_opts = {
  wait_time_seconds: RUBY_ENV == "production" ? nil : 5,
  attribute_names: %w(
    ApproximateReceiveCount
    SentTimestamp
  )
}
```

**Comment by phstc** [comment]
Hi @waynerobinson 

`Shoryuken.sqs_client_receive_message_opts` is the right way of doing it. [I updated the wiki with instructions](https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client#sqs-client).

Setting `attribute_names` is no longer needed, it's always `All` by default. This was required because of FIFO Queues.
