### ISSUE TITLE
lifecycle and queue creation

### ISSUE THREAD

**Issue by nicpillinger** [phstc/shoryuken#360]
Hi just trying to get up and running with this but cant seem to figure out how I can create queues when shoryuken starts up. I see you have lifecycle events but not sure where I can add that code to configure things as I need to. I'm not necessarily running a web process (although I probably will be eventually). thanks for any info!

**Comment by nicpillinger** [comment]
ok I've made it work by putting it into a method which the worker calls to get the queue.

 ```
 def self.setup_queues
    sqs = Aws::SQS::Client.new
    sqs.create_queue({ queue_name: 'staging-blah' })
    sqs.create_queue({ queue_name: 'production-blah' })

    # monitor the correct queue
    "#{ENV["APPLICATION_ENV"]}-blah"
  end

  shoryuken_options queue: -> {setup_queues}, auto_delete: true, body_parser: :json

```

**Comment by phstc** [comment]
Hi @nicpillinger 

Shoryuken is just a client for AWS SQS, you need to create the queues directly in the AWS Console or via scripts, for example a rake task or CloudFormation should do. Beware that the queues should be created once, in your snippet, it seems it will attempt to create them for every Shoryuken run.

[This post](https://www.sitepoint.com/quickly-process-api-requests-with-shoryuken-and-sqs/) from @williamkennedy can give you some guidance. It isn't using the latest Shoryuken, but it can give you an overall idea.

**Comment by nicpillinger** [comment]
pretty sure calling create queue on a queue which is already there has no effect. I understand what its for and it seems very useful - thanks! we have a large number of apps using SQS and I want each app to be responsible for queue creation and subscription to sns topics so I just needed a way of making sure queues exist for shoryuken starts polling. 

a rake task might be a better option, it just seems like a reasonable thing to want to do as part of shuryoken starting up

**Comment by phstc** [comment]
> pretty sure calling create queue on a queue which is already there has no effect

just tested and confirmed, it's like `create_or_find_by_name` - no exception is thrown. 

> a rake task might be a better option,

or CloudFormation, but if you are not using it already, it may introduce a lot of other complexities. 

The only issue with doing in that way, is because it will make a request against SQS, and AWS charges per request, but TBH it won't cost  "nothing".

> it just seems like a reasonable thing to want to do as part of shuryoken starting up

Makes sense. I isn't built in Shoryuken, because I don't know if the default queue setup works for everybody and I try to leverage the usage of the SDK directly as it's supported on it.

---

> we have a large number of apps using SQS 

Just out of my curiosity consuming with Ruby? If so, what were using before Shoryuken?

**Comment by nicpillinger** [comment]
@phstc We have apps in ruby/js and .net all using SQS. We've used the sdk directly for access in most cases. I'm going to have a look at how we might want to use shoryoken and if it looks like it could be useful for anyone else I'll PR it so you can take a look. cheers

**Comment by phstc** [comment]
@nicpillinger nice, sounds good. Let me know if you need any help 🍻

**Comment by nicpillinger** [comment]
@phstc should I have access to my rails environment inside the shoryuken worker? I dont seem to be able to see my models? I'm running Rails 5 as an api.

**Comment by phstc** [comment]
Hi @nicpillinger 

You should. Are you passing the `--rails` flag?

See https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job

**Comment by nicpillinger** [comment]
sorry didnt see that - not using activejob

**Comment by nicpillinger** [comment]
@phstc not sure how I can start a specific worker with the rails env loaded - it doesnt seem to be possible to to do -C ./worker and -R at the same time?

**Comment by phstc** [comment]
@nicpillinger have a look at `shoryuken help start`. `-C` is for the config file, not for requiring classes. You can load Rails and standard workers all together.

**Comment by nicpillinger** [comment]
@phstc cool - sorted needed -R and -r -C all good - thanks!

**Comment by andrhamm** [comment]
I was also trying to find the best way to create all the queues on bootup. I would love it if Shoryuken had support for this. Especially when using ActiveJob interface, anything that is SQS-specific makes it more difficult to seamlessly switch over to Shoryuken. As long as my SQS credentials have permission to create queues, Shoryuken should create them automatically if they don't exist.

**Comment by nicpillinger** [comment]
@andrhamm I ended up hooking into rails initialisation and creating queues there before shoryuken starts. It's sort of specific to our stuff at the moment but should be fairly simple to pull it out to a gem if it's useful. To be honest it would be a lot better if there was a lifecycle hook which allowed us to plugin to shoryuken before it validated the queues but I couldn't see an easy way of doing this.

**Comment by andrhamm** [comment]
@nicpillinger I'm hoping it would be considered as a Shoryuken improvement. Sidekiq, for example, automatically creates queues on bootup. If this were a core feature, then the only Shoryuken/SQS-specific configuration would be in `shoryuken.yml`. It would make getting started or switching to Shoryuken (at least from another ActiveJob integration) super easy.

**Comment by phstc** [comment]
@andrhamm the thing I'm worried about with auto creating queues is because `SQS != Sidekiq/Redis`, each queue may have different configurations, visibility timeout, FIFO, possible DL etc. I'm worried if Shoryuken auto creates queues with default settings it may cause issues for people that don't know how SQS works, for example double processing. 

It could be an option `auto_create_queues` (default false) something like that, so users would at least know that they are letting Shoryuken to create queues with default settings, WDYT?

**Comment by andrhamm** [comment]
@phstc I see the backwards compatability issues and I think that a config option defaulted to false is totally reasonable. I will say, however, it seems like it should always work this way with the ActiveJob interface, since the point of using a generic job interface like ActiveJob is really to mask the backend implementation to make it as compatible as possible with other integrations. I also think that the need to have multiple queues with different settings would be a bit of an odd requirement for what amounts to a "beginner" interface like ActiveJob. 👍

**Comment by phstc** [comment]
@andrhamm that's a valid point. The thing with multiple settings I agree, my concern TBH is more like "you should know what you are doing", but I'm not sure if not auto creating queues would guarantee that.

I'm reopening this. I'm fine with a `shoryuken.yml` setting `auto_create_queues` (default false) and being enabled by default for ActiveJob.

**Comment by andrhamm** [comment]
@phstc Awesome! I would be excited to see this feature. 🎉

**Comment by andrhamm** [comment]
@phstc i noticed your change didn't add any configuration options like `auto_create_queues`, did you decide against it?

**Comment by phstc** [comment]
@andrhamm I'm still letting the idea to seat properly. I guess, we can go with auto creating it always by default, if someone has a need for disabling it, we can add the option. WDYT?

**Comment by andrhamm** [comment]
@phstc I don't mind it this way at all, just something I noticed when reviewing the code. Any chance you'd release a beta version of the gem with this change?

**Comment by phstc** [comment]
@andrhamm check [this](https://github.com/phstc/shoryuken/commit/c48ff4159d853f2a73ec69a9180892be38ed24d1#commitcomment-22708658) from @algorist. Most likely I will release a new version after making a param default false.
