### ISSUE TITLE
Rescue in fetcher is too broad, should be given more specific exception classes

### ISSUE THREAD

**Issue by raquelxmoss** [phstc/shoryuken#369]
Hello!

I use Shoryuken at work to run several workers, and recently the `rescue` [here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/fetcher.rb#L19) has given us a bit of trouble. We've had a few instances where there have been failures (e.g. `Failed to open TCP connection to sqs ...`) that have been rescued. As such, they're not picked up by Rollbar, and the team is not alerted. We only find out our queue hasn't processed if we remember to log into the server in the morning and read the logs.

I wonder if you had considered being a bit more specific with the exception classes that are being rescued here?

Thanks 😄

**Comment by phstc** [comment]
Hi @raquelxmoss 

hm how did you get `Failed to open TCP connection to sqs`? Was it working, then it lost internet access? I'm wondering if the connection is something we need to check at startup. Actually, Shoryuken does while trying to get the queue URL: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/queue.rb#L12   

> . As such, they're not picked up by Rollbar

Even if it was raising up the error, I don't think it would be catch by Rollbar or similar trackers, since fetching is core Shoryuken and usually these trackers are triggered by workers, if a worker fails. Most likely raising up would kill the process or make it hang.

What I usually do is to configure CloudWatch alarms based on the queues Messages Available/Inflight, it the size is bigger than what it should for a given period of time, I get notified by email/Slack. Would that help you?

I'm totally open for discussing alternatives.

**Comment by raquelxmoss** [comment]
Hey @phstc, I'm not sure how we managed to get the failed TCP connection, we're still looking into it but haven't made much headway. It appears that yes it was working (on an AWS EC2 instance), but I haven't figured out how it lost the connection. The worker never regained the connection, and had to be manually restarted. Ongoing mystery that we're still looking into 😅.

The CloudWatch alarms might be tricky in our case, as I don't think we can really nail down the business logic of how many messages 'should' be there at a given period of time, I'll have a think about it though.

I'm still curious about not raising up the error
> Most likely raising up would kill the process or make it hang.

In my case, having the error raise and kill the process might be more desirable -- it would trigger a restart, which would re-establish the TCP connection.

**Comment by phstc** [comment]
Hey @raquelxmoss 

> In my case, having the error raise and kill the process might be more desirable -- it would trigger a restart, which would re-establish the TCP connection.

Makes sense, but I need to think more on it. Feels like a major change.

TBH I've never faced this issue of losing the connection. I'm kinda worried if it's something that happens more often, and might be better to retry (rescuing) since it may work in the next attempt than killing the process. 

I guess it's a matter of trade offs: Killing the process is better for those monitoring the process, retrying is better in case it's something momentarily. 

I'm not against of changing it, I'm just lopping through the possibilities. I'm inclined to go with your suggestion.

> The CloudWatch alarms might be tricky in our case, as I don't think we can really nail down the business logic of how many messages 'should' be there at a given period of time, I'll have a think about it though.

No matter if we change Shoryuken or not, I believe that's the best for any SQS setup.

**Comment by raquelxmoss** [comment]
Cool, thanks for that response. If I find out _why_ the loss of connection occurred I'll let you know, as it might be relevant. Happy to have you mull it over and decide whether to act or leave things as-is.

**Comment by phstc** [comment]
> In my case, having the error raise and kill the process might be more desirable -- it would trigger a restart, which would re-establish the TCP connection.

@raquelxmoss thinking more on it. How a process restart would re-establish the TCP connection? If your instance lost the connection, restarting the process wouldn't solve it.

Just confirming the problem, Shoryuken was logging out `Failed to open TCP connection to sqs ...` then you killed and started it again and everything worked fine?

**Comment by raquelxmoss** [comment]
@phstc Yes, that's correct 👍

**Comment by phstc** [comment]
@raquelxmoss that seems strange. Like restarting the Ruby process, then the connection gets back. Did you restart the instance or just the process?

**Comment by raquelxmoss** [comment]
@phstc I did a `sudo service my_thing stop` then `sudo service my_thing start`

**Comment by phstc** [comment]
@raquelxmoss how is your shoryuken.yml configured? I'm wondering if your configuration uses ENV variables, that were causing the `TCP connection error`, then you deployed a new version or changed some ENVs without restarting the process. ENV changes only "propagate" after restarting the process.

**Comment by MichaelDowse** [comment]
Hey @phstc, I'm working on this with @raquelxmoss.

We've been running a forked version of Shoryuken which raises errors for a few days now and we're happy that this is the behaviour we want. I have submitted #374 to make this a configurable option, let me know what you think.

**Comment by phstc** [comment]
Hi @MichaelDowse 

Cool, I've just commented in your PR 🍻 

> @raquelxmoss how is your shoryuken.yml configured? I'm wondering if your configuration uses ENV variables, that were causing the TCP connection error, then you deployed a new version or changed some ENVs without restarting the process. ENV changes only "propagate" after restarting the process.

Any thoughts on that?

**Comment by raquelxmoss** [comment]
@phstc Oh sorry -- we don't use a `shoryuken.yml`

**Comment by phstc** [comment]
@raquelxmoss no problem. The fix will be available in the upcoming release 🍻

**Comment by phstc** [comment]
@raquelxmoss @MichaelDowse Shoryuken 3.1.0 is out with your change 🍻
