### ISSUE TITLE
Handling of failed delete_message_batch response

### ISSUE THREAD

**Issue by andrewyoo** [phstc/shoryuken#370]
I am running a shoryuken worker (v3.0.6) on a queue with max receive 1 then going to a dead letter queue.  I ran thousands of jobs and this job ran successfully according to my logs, but appeared in my dead_letter queue.

````
2017-05-24T22:47:05Z 17351 TID-t5ixk ActiveJob/PaymentCreatorJob/production_payments/42c685e1-af52-4101-9e96-e45a02a0a0b2 INFO: started at 2017-05-24 18:47:05 -040
2017-05-24T22:47:07Z 17351 TID-t5ixk ActiveJob/PaymentCreatorJob/production_payments/42c685e1-af52-4101-9e96-e45a02a0a0b2 INFO: completed in: 2055.410412 ms
````

````
Message ID:	42c685e1-af52-4101-9e96-e45a02a0a0b2
Size:	166 bytes
MD5 of Body:	b9ed8d527272547ef9d44f7aacf1c587
Sender Account ID:	AIDAI74XCYUP6XVXP3CLO
Sent:	2017-05-24 18:31:11.496 GMT-04:00
First Received:	2017-05-24 18:31:11.496 GMT-04:00
Receive Count:	5
Message Attribute Count:	1
````

Inspecting the dead letter queue is why receive_count is at 5. Also I don't know why, but SQS is displaying the wrong First Received time at the moment. (I swear it was accurate on previous inspections in aws console)

Anyway I suspect ````delete_message_batch```` may have failed silently.  Since it's a batch delete request, it may return with a valid 200, but have actual failed response.

My jobs are idempotent so I plan to up the retries to 2, but this is a bit disconcerting.  I will investigate further, but I think it is fairly important to know my job was processed and shouldn't be double run.

**Comment by phstc** [comment]
> Anyway I was suspect delete_message_batch may have failed silently. Since it's a batch delete request, it may return with a valid 200, but have actual failed response.

@andrewyoo failing at batch deleting isn't something I saw before.  But I understand your assumption. Any chance this message took longer than the visibility timeout on these 5 receives? The one you showed in the issue took ~2 secs, so it's unlikely... just asking... 

I'm thinking on a few options:

- [here](https://github.com/phstc/shoryuken/blob/a40e6b26e2dfbc4a78a36198d02010dce66a977e/lib/shoryuken/middleware/server/auto_delete.rb#L15) call [`delete_message`](https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#delete_message-instance_method) if `entries.one?` instead of [`delete_message_batch`](https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#delete_message_batch-instance_method)
- [here](https://github.com/phstc/shoryuken/blob/11772dd8e4dba93e8a753c2f073fcb7b1b1b6690/lib/shoryuken/queue.rb#L22) warn if `failed.any?`

**Comment by andrewyoo** [comment]
@phstc I should have mentioned it, but it did finish well before the visibility timeout of 2 minutes. 

I don't even know what the correct thing to do here since the job did complete successfully. Maybe your 2nd suggestion of a warning in the log. I'm going to see if i can log my sqs requests/responses to see what a potential error response would look like if aws returned some odd response to the ````delete_message_batch````

**Comment by phstc** [comment]
Hi @andrewyoo 

Could you have a look at #371? I added the logging we talked about.

Receiving it five times is too much, but I'm wondering if 👇 could be the case.

> The receipt handle is associated with a specific instance of receiving the message. If you receive a message more than once, the receipt handle you get each time you receive the message is different. If you don't provide the most recently received receipt handle for the message when you use the DeleteMessage action, the request succeeds, but the message might not be deleted.

or

> For standard queues, it is possible to receive a message even after you delete it. This might happen on rare occasions if one of the servers storing a copy of the message is unavailable when you send the request to delete the message. The copy remains on the server and might be returned to you on a subsequent receive request. You should ensure that your application is idempotent, so that receiving a message more than once does not cause issues.
> https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#delete_message-instance_method

Are you using Shoryuken Workers or ActiveJob?

I'm still considering calling `delete_message` when a single entry (most cases), but TBH I don't know if it would help, it would be just a guess attempt, WDYT?

**Comment by andrewyoo** [comment]
I'm using ActiveJob with shoryuken.

If aws is stating that for "standard queues", delete requests may not go through and jobs should be idempotent then there's not much we can do other then write our jobs idempotently. I think all shoryuken can do is log it.

Makes me wonder for some sensitive queues the job should be deleted first, then executed, then re-queued if failed. 

I just read looking up what the alternative to "standard queue" is and it looks like maybe what i need to use the the **FIFO queue**

> If you have an existing application that uses standard queues and you want to take advantage of the ordering or **exactly-once processing** features of FIFO queues, you need to configure the queue and your application correctly.

I'm highly sensitive to this because my company runs payments and the last thing we want to do is accidentally double pay a lot of people 😱 

Thanks for thinking this one out with me.

**Comment by phstc** [comment]
@andrewyoo makes sense, I will move forward with the logging then.

I hear you. I think FIFO is a good idea for jobs that can't be processed more than once. Specially for payments, since we can't "workaround", like removing a wrong statement. Actually, for any integration with external systems, as we can't fully control them.

BTW In case you are using Stripe, [their idempotency_key](https://stripe.com/docs/api/ruby#idempotent_requests) might be interesting for you.
