### ISSUE TITLE
Unique jobs for Shoryuken?

### ISSUE THREAD

**Issue by Spazer9** [phstc/shoryuken#385]
Is there a way to ensure jobs with the same arguments only execute once in parallel?

Sort of like Sidekiq unique jobs where you can make sure certain workers never execute two jobs with the same arguments at the same time, in parallel. (which results in race conditions with DB in some cases).

**Comment by phstc** [comment]
Hi @Spazer9 

Have a look at [FIFO queues](https://github.com/phstc/shoryuken/wiki/FIFO-Queues). Amazon SQS has built in features for preventing duplicated messages sent during a 5-minute interval, and also First In, First Out support.

If you can ignore duplicated messages, probably [Message Deduplication ID](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-understanding-logic) can work for you. If you can't ignore dups, you may need to work with a Message Group ID, but it may be trick with Shoryuken, you will need to keep a single process with a single thread (concurrency), otherwise the multi threading will give some "parallelism" for the group id.

**Comment by Spazer9** [comment]
Thanks Pablo for the ideas. I just realized there's FIFO queues now on AWS. however i went with a different direction that involves Redis locks (which i actually hope it becomes a native shoryuken feature - i love your gem by the way).

The way I make sure same-argument jobs never execute concurrently is by using **redis-objects** gem which exposes a useful **redis lock & unlock** feature:

```
class SlowWorker
  include Shoryuken::Worker

  def perform(sqs_msg, data)
    # Lock jobs based on passed account_id
    Redis::Lock.new("slow_worker:#{data["account_id"]}", expiration: 30, :timeout => 0.5).lock do
      # Do work that is race-condition prone

      # as soon as the code executes, it releases the lock and allows other workers to execute this code block
      # If other worker tries to execute this at the same time as another worker, it'll raise an exception
    end

  end
end
```

**Comment by phstc** [comment]
Hi @Spazer9 

You need to be very careful with that lock, since SQS is time sensitive (see [`visibility_timeout`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html)), it may cause your messages to get back to the queue, which can be a problem, specially if you use DL queues.

> which i actually hope it becomes a native shoryuken feature

I try to keep Shoryuken as transparent as possible to SQS, so it's unlikely to have some sort of Redis dependency on Shoryuken. 

Another option for your Redis lock could be a middleware. BTW a middleware could be also a Gem in case you are interested on creating one. There are other gems ([see this](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/plugins/shoryuken.rb#L45-L48)) that auto adds middleware to Shoryuken.

**Comment by Spazer9** [comment]
@phstc Gotcha!

Thanks for the heads up regarding the `visibility_timeout`. although I'm not sure 100% how a failed case would look like and what would cause it when I use redis lock? (would that happen if a certain exception rises for example? or because a  lock takes too long to acquire?)

I'm not very versatile with SQS to be honest. i'd really appreciate it if you enlighten :)

**Comment by phstc** [comment]
Hi @Spazer9, check [Message Lifecycle](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-lifecycle.html) for some guidance on the SQS lifecycle. 

Do all your jobs need to be processed in that way (sequentially) or just a few of them?

**Comment by Spazer9** [comment]
Hey @phstc 

Only 1-2 workers need to be done this way (basically longer jobs triggered by a recurring cloudwatch event. these jobs go over a long list of accounts and execute some DB operations. that's why i'm worried about parallelism for those workers)

Other workers i'm not really worried about.

I've read a bit about SQS's visibility timeout now - Wouldn't setting `auto_visibility_timeout` to true mitigate this issue?

**Comment by phstc** [comment]
In general, it isn't a good practice to have long running jobs. Specially if they are just waiting for another job.

I still want to get back to #347, so you would be able to configure a queue with concurrency 1, and all others with the concurrency you want. The one with concurrency 1, you could use FIFO to make sure Shoryuken will process only one message per group id at time. Meanwhile, an alternative would be to run Shoryuken with concurrency 1 (which will be applied to all queues/workers), since #347 isn't done yet.

**Comment by oyeanuj** [comment]
@phstc This part of your response caught my eye, so I thought I'd clarify (even though this thread isn't relevant for me):

> In general, it isn't a good practice to have long running jobs. Specially if they are just waiting for another job.

I was wondering if you could elaborate on this? Maybe this is something we could add to the "Best Practices" section. In my case, I'm using this library to send sign-up/password/registration emails. These jobs are sporadic atm but I wanted to pass it to a background process with `long polling`. Would you consider this a legit use-case?

**Comment by phstc** [comment]
@oyeanuj the idea is that, if you have a process that renews 100 subscriptions: Instead of having a single to loop in your worker to renew all subscriptions, one by one at a time, you could have a dispatcher to enqueue a job per subscription. So if a subscription fails to renew, it is going to fail just a single subscription instead of the whole batch. 

This is just an example, there are a lot of benefits of smaller and faster jobs (more granular). But those depend on each use-case.

Does that make sense?
