### ISSUE TITLE
Override worker delegation convention

### ISSUE THREAD

**Issue by maschwenk** [phstc/shoryuken#403]
I have some messages coming onto my SQS queue that don't come from `shoryuken` but I'd like them to be handled by an ActiveJob worker. The source of the notifications is not configurable to hardcode the worker class (they come from ASG autoscaling SNS). Is there any _good_ (I'll take hacky as well 😉 ) way to get inside the delegation code and introspect the messages and re-route them to the correct ActiveJob classes?

Perhaps with a middleware?

**Comment by phstc** [comment]
@maschwenk you can use a custom worker registry for routing messages, see [this](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L15).

Does that work for you?

**Comment by maschwenk** [comment]
👍  thanks! Would you be open to me creating a PR to improve the wiki for this? Although I'm sure non-shoryuken messages aren't something you'd want to spend a ton of time supporting, SQS is one of the most common endpoints for SNS messages so it might be worth including.

**Comment by phstc** [comment]
@maschwenk I would love a wiki for that. I wrote a quick page for that https://github.com/phstc/shoryuken/wiki/Worker-registry, would you mind to review it? Feel free to change.

Not sure how is your full setup, but if you use Shoryuken workers instead of ActiveJob, you can associate a worker to a queue. You can configure a ActiveJob job and a regular Shoryuken Worker to the same queue, the queue that receives the non standard messages, because of [this](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L24), most likely all non-standard messages will be processed by the Shoryuken worker.

**Comment by maschwenk** [comment]
I updated the Wiki a bit. I did want to add one clause saying:

the worker you register _cannot_ be a ActiveJob, it must be a Worker

I'm not sure if that's true but I when I tried to register a ActiveJob it was not working (which I guess makes sense)

**Comment by phstc** [comment]
@maschwenk the worker for ActiveJob is always [`JobWrapper`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L72). `ActiveJob::Base.execute` is the one responsible for finding the appropriated  `< ActiveJob` job.

> the worker you register cannot be a ActiveJob, it must be a Worker

So that ^ isn't wrong, the maximum you would be able to do is to call something else other than `JobWrapper`. Have a look at the [`hash`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L77) content, might be something in there telling which job should be called.
