### ISSUE TITLE
Integrating CloudWatch Events with SQS and Shoryuken

### ISSUE THREAD

**Issue by ancaciascaiu** [phstc/shoryuken#421]
My team and I are trying to set up a CloudWatch event for a project that uses Shoryuken.
We've tried different json formats for the message that needs to be specified when setting up a CloudWatch Rule (the rule is a scheduled CloudWatch event that also specifies the contents to be triggered).
One such example that we though is really close to what we needed is:

```json
{
  "job_class": "ThisBeautifulJob",
  "job_id": "00000000-0000-0000-0000-000000000000",
  "queue_name": "this_beautiful_job_report",
  "priority": null,
  "arguments": [],
  "locale": "en"
}
```

The observation we were able to make is that CloudWatch can't set the Message Attributes in the way we specified them.
Is there a specific way we need to shape our json, according to what Shoryuken expects?

Thanks,
Anca

**Comment by phstc** [comment]
Hi @ancaciascaiu 

Without the message attribute, my suggestion would be to use a [Standard Shoryuken Worker](https://github.com/phstc/shoryuken/wiki/Worker-options#queue) instead of Active Job. Standard Workers aren't opinionated on the message format, and can be [mapped one-to-one to a queue](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L24).

```ruby
class MyWorker
  include Shoryuken::Worker

  shoryuken_options queue: 'this_beautiful_job_report', auto_delete: true
  
  def perform(sqs_msg, body)
    # ...
  end
end
```

☝️ all the messages enqueued to `this_beautiful_job_report` will be consumed by `MyWorker`.

If you do need to use ActiveJob, another option might be [a custom worker registry](https://github.com/phstc/shoryuken/wiki/Worker-registry).
