### ISSUE TITLE
Job title not displaying in logs

### ISSUE THREAD

**Issue by bnolan** [phstc/shoryuken#442]
I'm inserting SQS jobs using a node.js script, the inserted job looks like:

```{"job_class":"CountFarmsJob","job_id":"eee140b0-d010-4ccb-abb4-69362778e653","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[],"executions":0,"locale":"en"}```

And the job runs fine, but shoryuken fails to display the job title in the logs, making debugging difficult. This is what one of these jobs look like in the logs:

```
2017-11-08T22:27:20Z 198 TID-s6p10 ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper/default/78075588-cb6a-407f-b487-5c397adfa5a4 INFO: completed in: 11.814053 ms
```

Any idea what might be causing this? The JSON of the jobs created by our node.js process is identical to the JSON of jobs inserted by calling `CountFarmsJob.perform_later`.

**Comment by bnolan** [comment]
The correct job logging should be:

```2017-11-08T22:21:35Z 198 TID-s6p10 ActiveJob/CountFarmsJob/default/ec071be1-2756-4ac8-8227-8c9614494ea1 INFO: started at 2017-11-08 22:21:35 +0000 
```

**Comment by phstc** [comment]
Hi @bnolan 

It's because [`JobWrapper`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L72) is the "real" Shoryuken worker when using ActiveJob. This only happens when using ActiveJob, if you use a regular Shoryuken worker, it logs out the right worker.

But indeed, it does not help with debugging.  [Sidekiq tries to lookup the context for ActiveJob](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/logging.rb#L34), it can be an alternative to be patched in Shoryuken.

**Comment by phstc** [comment]
Hi @bnolan 

Actually, giving a second look at this issue, the Active Job was already fixed a time ago. Which version of Shoryuken are you using?

```
2017-12-22T22:59:12Z 27164 TID-ovdzgmd24 INFO: Starting
2017-12-22T22:59:12Z 27164 TID-ove016qto ActiveJob/TestJob/test.fifo/f4ecac31-... INFO: started at 2017-12-22 17:59:12 -0500
2017-12-22T22:59:12Z 27164 TID-ove035w60 ActiveJob/TestJob/test.fifo/300ac9a7-... INFO: started at 2017-12-22 17:59:12 -0500
2017-12-22T22:59:12Z 27164 TID-ove0358nc ActiveJob/TestJob/test.fifo/9f940c71-... INFO: started at 2017-12-22 17:59:12 -0500
```

I created a test project for testing it out, and the real worker name `TestJob` showed up properly.

**Comment by phstc** [comment]
@bnolan are you using `batch` workers? If so, it might be an issue https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/util.rb#L34
