### ISSUE TITLE
Processing slows-down with only one type of job

### ISSUE THREAD

**Issue by alexvollmer** [phstc/shoryuken#468]
I'll apologize in advance for filing an issue here in GH, when I'm pretty sure I'm just using Shoryuken incorrectly. But after looking through previous issues, re-reading the SQS docs and the wiki I'm at my wits' end with this one.

I'm using Shoryuken/SQS to power a webcrawl, with a different job class for each discrete class of work (e.g. RSS feed-fetching, sitemap parsing, document fetching, document indexing etc.). That last job, indexing, is always the one that gets executed the most. We use a "critical" queue for indexing jobs with a 4x priority over the "default" queue, which handles all the other work.

What I've observed is that our throughput rate for indexing changes dramatically based on whether or not there are other job types to perform. When we kick off a crawl and perform all the other jobs we often hit high-water rates of 500 docs/minute. But, somewhat counter-intuitively, when we _just_ have indexing work, our throughput drops to below a tenth of that.

When the system is in this state and I look in the logs, the activity looks very "bursty". I see 10 jobs processed every twenty seconds. I'm assuming this is due to configuring the queues for long-polling with this:
```
Shoryuken.sqs_client_receive_message_opts = {
  wait_time_seconds: 20
}
```
If that's the culprit, how does one balance the cost-savings of long-polling with getting through a backlog of jobs in a reasonable amount of time?

Again, sorry if I missed any obvious RTFM. We switched from Sidekiq to Shoryuken and it has been fantastic for us, other than this one (likely self-induced) hiccup.

Thanks!

**Comment by phstc** [comment]
@alexvollmer no need for apologizes. I will be happy to help.

I'm not sure if I followed the problem completely, so I will give you a more broad feedback, I hope it helps.

---

There's also the concurrency, which by default is 25. Depending on your active jobs I/O or CPU Bounds, you won't have as many threads available for processing. That can cause the differences in throughput depending on the work load.

If the concurrency is the problem, there's no real magic number for that, you need to play with that based on your work load.

If you want to enforce a queue priority, have a look at [Strict Priority](https://github.com/phstc/shoryuken/wiki/Polling-strategies#strictpriority).

> If that's the culprit, how does one balance the cost-savings of long-polling with getting through a backlog of jobs in a reasonable amount of time?

You can also create multiple [processing groups](https://github.com/phstc/shoryuken/wiki/Processing-Groups), so the long polling from one queue, wouldn't affect the other directly.

Cost is very complex to calculate, since it will depend on the number of factors, such as the number of process/pollers, [delay](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#delay) etc. SQS charges per request, the more you make, the more you pay. Long poll and delay can reduce the number of requests, but on the other hand they can down the throughput.

**Comment by alexvollmer** [comment]
@phstc thanks for the quick response. Thanks for the pointers to processing groups, delay and strict priority. I'll take a look at those. Two follow-up questions:

Does the behavior I explained where job throughput for a single task-type (i.e. `Shoryuken::Worker`) in a single queue slows down due to the absence of other work for other tasks in other queues? Just for my own edification, I'd like to understand what causes that.

Secondly, does the Shoryuken API support modifying the wait-time dynamically? For example, when I'm able to detect a large load like this, adjust the wait-time to zero and then return it to a different level after a few polls with no results? More importantly, is that a smart thing to do, or am I looking at the problem incorrectly?

Thanks again for your help and this fantastic tool!

**Comment by phstc** [comment]
> Does the behavior I explained where job throughput for a single task-type (i.e. Shoryuken::Worker) in a single queue slows down due to the absence of other work for other tasks in other queues? 

@alexvollmer It should not. But the absence of messages in a queue combined with delay can pause fetching, if you are using multiple workers for the same queue.

> Secondly, does the Shoryuken API support modifying the wait-time dynamically? For example, when I'm able to detect a large load like this, adjust the wait-time to zero and then return it to a different level after a few polls with no results?

You can change the the `wait_time_seconds` dynamically. See [Long Poll](https://github.com/phstc/shoryuken/wiki/Long-Polling). 

>  More importantly, is that a smart thing to do, or am I looking at the problem incorrectly?

Get up to speed with all the options: long poll, delay, processing groups, multiple workers per queue or single worker per queue. That will help you out to understand the big picture better. Usually changes for saving costs on AWS SQS are not worth, double check the SQS price and your volume before premature optimizations.

**Comment by alexvollmer** [comment]
Awesome. Thanks!
