### ISSUE TITLE
Implement TSTP a-la Sidekiq for signaling future deploy

### ISSUE THREAD

**Issue by HoneyryderChuck** [phstc/shoryuken#479]
We're using Shoryuken, and would greatly benefit from a similar feature to [Sidekiq's TSTP signal handling](https://github.com/mperham/sidekiq/wiki/Signals#tstp), meaning "stop consuming the queue and finish your work, because the process will die soon".

As I understood, shoryuken was a Sidekiq fork. Was the removal of this signal a decision based on some limitation of the SQS client integration, or could this be done?

**Comment by phstc** [comment]
> As I understood, shoryuken was a Sidekiq fork. Was the removal of this signal a decision based on some limitation of the SQS client integration, or could this be done?

@HoneyryderChuck it was more of a copy of main components, like than Celluloid implementation. I couldn't make it a fork (I tried it), since SQS differed drastically from Redis.

I didn't implement TSTP, because I didn't have a use for it, but it can be done. 

Unless I'm missing something, It should be pretty much what Shoryuken does for [`USR1`](https://github.com/phstc/shoryuken/blob/2f7289df2871fc652d5c9e8c0faab0e0f95817ac/lib/shoryuken/runner.rb#L124), but without the `exit 0`. I'm open for pull requests, in case you are interested to work on it.

**Comment by HoneyryderChuck** [comment]
@phstc we'll access the feasibility and get back at you shortly. It would have significant impact in our case.

**Comment by sideshowdave7** [comment]
@HoneyryderChuck Are you working on this? This would also be useful in my situation and would be happy to make a PR for it.

**Comment by phstc** [comment]
Wiki updated https://github.com/phstc/shoryuken/wiki/Signals#tstp 🎉
