### ISSUE TITLE
Retrieving SQS Message ID using ActiveJob job instances.

### ISSUE THREAD

**Issue by allomov** [phstc/shoryuken#485]
Hello, everyone.

We use modular rails architecture together with jobs based on ActiveJob, one of the gems contains all base jobs that application should run and another can decide what adapter to use.

The thing is that we want to store SQS message ID if it possible in case when we use shoryuken. From [what I can see you](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L82-L91), you use a wrapper for such cases, which prevents access to `sqs_msg`.

Could you tell if I missed something and how if there is a way to retrieving SQS message ID inside Rails application without including `Shoryuken::Worker`? Thank you.

**Comment by phstc** [comment]
@allomov For getting the `sqs_msg` you need to use standard workers instead of ActiveJob. ActiveJob interface does not support any extra param (such as the `sqs_msg`), besides what you passed in with `perform_later`.

If you need to store the message ID, you need to use standard workers.

Could you give more details on the need of storing the message ID?
