### ISSUE TITLE
Bumping down log levels

### ISSUE THREAD

**Issue by Erol** [phstc/shoryuken#499]
What do you think about changing the log level from `info` to `debug` for calls like below?

https://github.com/phstc/shoryuken/blob/7d3331b977631f17dd280189bac3d27ae63cd4e0/lib/shoryuken/middleware/server/timing.rb#L10

https://github.com/phstc/shoryuken/blob/7d3331b977631f17dd280189bac3d27ae63cd4e0/lib/shoryuken/middleware/server/timing.rb#L20

https://github.com/phstc/shoryuken/blob/7d3331b977631f17dd280189bac3d27ae63cd4e0/lib/shoryuken/middleware/server/timing.rb#L22

**Comment by Erol** [comment]
My specific use case is to cut down on logs emitted on Sumo Logic. We are emitting useful messages - such as requests - as `info`, and was wondering if the calls above are better delegated to `debug`.

**Comment by rmharrison** [comment]
My feel is that timing information goes in debug, is output with a flag (e.g. `--dev`, `--performance`, `--profiling`) or into its own log stream.

Problem is, minor/patch change and folk's app monitoring breaking is mean. Changing the log level could be a breaking change for folks, ergo cleanest in a major version bump. :face_with_head_bandage:

**Comment by Erol** [comment]
That's a fair point. How about a deprecation, plus an optional config to control how timing is logged?

**Comment by rmharrison** [comment]
Timing flag feels a bit bloaty, but you're right it wouldn't be breaking.

Given that this lib recently took a log-level change as patch and no one whinged, I'd K.I.S.S. on the options and just info --> debug in a patch **as long as there is another info level event indicating for each transaction** (otherwise, you wouldn't know when your workers are active).
