### ISSUE TITLE
Handle AWS::SQS::Errors::InternalError exception

### ISSUE THREAD

**Issue by manhdaovan** [phstc/shoryuken#502]
I have many running jobs using Shoryuken and sometimes I received some errors from AWS::SQS::Errors::InternalError exception and Shoryuken kill the process as at here:

https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L46

But that means all jobs will be stopped unexpectedly.

So how do you think about something like `retry` if the process doesn't deserve killing by some specific exception? 

Or how can I handle exceptions like this without killing the process?

**Comment by manhdaovan** [comment]
Hi @phstc 
Thank you for your reply.
I agree that there's no silver bullet solution.

My services were published 3 months ago, and the error occurred first time yesterday.
Of course, I'm not sure this occurs in future or not.
I've thought about "monkey patching", but it not mature solution at all.

How do you think about adding more param(s) to config Shoryuken to auto-retry with some specific exceptions? 
And when the exception occurred, Shoryuken will auto-retry or killed by reading this flag.
(Param(s) could be command line options or be defined in `.env` file or something like that.)

**Comment by phstc** [comment]
> How do you think about adding more param(s) to config Shoryuken to auto-retry with some specific exceptions?

Configuration/Param is usually a good way to make it customizable. But since this isn't a common request, I would rather not to, in favor of keeping it simple and easier to maintain. 

> but it not mature solution at all.

For making it more robust, I would recommend to monitor your process and restart it if it stops/crashes. 

Keep in mind that [USR1 is a soft shutdown](https://github.com/phstc/shoryuken/wiki/Signals#usr1), it shouldn't interrupt the current work load. The messages shouldn't go back to the queue.

`AWS::SQS::Errors::InternalError` should not happen often.
