### ISSUE TITLE
Manually retry failed jobs

### ISSUE THREAD

**Issue by Ayliane** [phstc/shoryuken#506]
Hi !
I'm trying to build an admin dashboard to monitor and manage our sqs queues, so we can see how many of them fail, restart them manually or destroy them. 

Of course, we have a retry interval set up and it's working just fine most of the time.

I've created a middleware as found in your documentation, and storing failed jobs informations in redis. 
I've been searching for a while now, and i can't find how to retry immediately and "manually" a failed job with shoryuken.

Does anyone have a clue ? 

Thanks a lot !

**Comment by phstc** [comment]
Hi @Ayliane 

Are you using [dead letter queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html)? I usually configure a dead letter queue and requeue the messages using the CLI: `shoryuken sqs mv dl-queue queue`, sometimes I also dump `shoryuken sqs dump dl-queue` and programmatically requeue only the ones I want to using `shoryuken sqs requeue queue requeue.jsonl`.

You can try to implement something similar in your dashboard, and I would recommend to use DL queues, since it is more like the "SQS way".

BTW @epintos built a dashboard for SQS as well, check [his post](https://medium.com/wolox-driving-innovation/asynchronous-processing-using-sqs-and-shoryuken-2596aec19b4c) - maybe it can give you some guidance.
