### ISSUE TITLE
RequestStore per executing/procession message

### ISSUE THREAD

**Issue by sonam-gupta** [phstc/shoryuken#527]
Hi,
I wish to know that, how can we store globally some information in request store, for per message execution of a worker. I am having trouble that the information used by the previous message is still available for the next message.

**Comment by phstc** [comment]
@sonam-gupta in theory the messages shouldn't have a dependency on each other. What's your use-case? Maybe a FIFO queue could be an option.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html

**Comment by sonam-gupta** [comment]
@phstc The use case is that I set some context which is been used globally for a message processing using RequestStore gem, so that context is specific to that message being processed. So ideally the context of one message shouldn't overlap with the other message. But thats not happening. So which to know, how this can be handled.

**Comment by phstc** [comment]
@sonam-gupta I don't think RequestStore will work. Shoryuken is multi-thread, there's no way to guarantee that a thread used for a message will be re-used (therefore its value set) for another message. If you want to have a global state like that, you need to use an external database for shared state. Or consider FIFO, it may work for you, since you can control the processing order.
