### ISSUE TITLE
How many SQS 'requests' are sent by Shoryuken?

### ISSUE THREAD

**Issue by MSCAU** [phstc/shoryuken#586]
A few days into the month I am concerned that I have already received a warning from AWS that my app has sent 85% of the 1,000,000 free-tier requests to SQS. Unless I am missing something, this is way too high as in that time period I've probably fired off less than 100 ActiveJob requests.

Does Shoryuken poll SQS every few seconds and create a "request" that way? In other words, I wonder whether AWS is billing for polling and not just jobs being enqueued.

**Comment by phstc** [comment]
Shoryuken will continuously poll (request to SQS for receiving messages) whenever [there are available threads](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency).   

You can reduce that by [configuring a delay for empty queues](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#delay) or using [Long polling](https://github.com/phstc/shoryuken/wiki/Long-Polling).

It is hard to determine the number of requests to SQS since it depends on each app/configuration.  But usually, batch receive (request), then delete (request), then batch receive (request) and so on.
