### ISSUE TITLE
request: allow queues in shoryuken.yml to be provided as ARN values

### ISSUE THREAD

**Issue by nippysaurus** [phstc/shoryuken#602]
I'm writing a CDK template for deploying an application with a lot of Shoryuken queues. Everything in AWS is using the ARN, but Shoryuken only works with URL and not ARN. These values are easy translated from one format to the other, but with so many queues it would still be a lot of mapping values in my code to do the translation. It would be super convenient if Shoryuken would do this for me.

[Here you can see how the AWS CDK template does the mapping](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sqs/lib/queue.ts#L200)

**Comment by phstc** [comment]
Hi @nippysaurus 

[Shoryuken can work with queue name or URL](https://github.com/phstc/shoryuken/blob/3ed8eb10ff59cc0fa81389890d13c826d45ae3a4/lib/shoryuken/queue.rb#L69).

[You can get `queueUrl` and `queueName` with CDK](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.Queue.html#queuename-1).

You could also output then.

```typescript
new cdk.CfnOutput(this, "QUEUE_URL", { value: queue.queueURL });
new cdk.CfnOutput(this, "QUEUE_NAME", { value: queue.queueName });

```

[The AWS SDK Ruby expects `queue_url` for interacting with a queue](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SQS/Client.html#send_message-instance_method), so the conversion is required. 


There are also some alternatives, for example, converting from ARN to URL or Name in your `shoryuken.yml`, it is an ERB. You can add code in there. Also, instead of adding queues via the `shoryuken.yml` you could add them programmatically [`Shoryuken.add_queue(...)`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/options.rb#L48) in an initializer. 

I don't recall previous requests for that, but I'm open to pull requests if the logic makes sense in case you are interested in submitting one.

**Comment by nippysaurus** [comment]
Yeah it's easy to do the mapping, but with the URL and ARN being so easily translated it would be nice to be able to supply either and have Shoryuken figure out what it is.

I took your advice and did the mapping in the config.

```ruby
# config/initializers/shoryuken.rb
def SqsArnToUrl(arn_str)
  return unless arn_str

  arn = Aws::ARNParser.parse(arn_str)

  raise "please pass an shoryuken queue ARN with region, account_id, and resource values (#{arn_str})" if [
    arn.region,
    arn.account_id,
    arn.resource
  ].any? { |value| value == "" || value == nil }

  `https://sqs.#{arn.region}.amazonaws.com/#{arn.account_id}/#{arn.resource}`
end
```

It would be great if this was in the Shoryuken framework though.

**Comment by phstc** [comment]
@nippysaurus yay I'm happy it worked! The code makes sense to me. Would you like to submit a PR?

[`name_or_url`](https://github.com/phstc/shoryuken/blob/3ed8eb10ff59cc0fa81389890d13c826d45ae3a4/lib/shoryuken/queue.rb#L11) will need to be changed to `name_or_url_or_arn`, but it is fine.  We should only check for the `arn` if the string starts with `arn:`.

**Comment by phstc** [comment]
Minor code tweak:

```ruby
def queue_url_from_arn(arn_str)
  arn = Aws::ARNParser.parse(arn_str)
  required = [arn.region, arn.account_id, arn.resource]

  raise "please pass an shoryuken queue ARN with region, account_id, and resource values (#{arn_str})" if required.any?(&:empty?)

  "https://sqs.#{arn.region}.amazonaws.com/#{arn.account_id}/#{arn.resource}"
rescue Aws::Errors::InvalidARNError
  raise "Invalid ARN: #{arn_str}"
end
```

**Comment by nippysaurus** [comment]
Thanks @phstc :) I'll try and put in some effort to get an MR up this week.

**Comment by nippysaurus** [comment]
https://github.com/phstc/shoryuken/pull/603

**Comment by phstc** [comment]
Added to 5.0.5

https://github.com/phstc/shoryuken/pull/603#issuecomment-640119230
