### ISSUE TITLE
How to read configuration to send tasks to worker?

### ISSUE THREAD

**Issue by janpapenbrock** [phstc/shoryuken#68]
First of all, thank you for this useful gem!

---

Sadly I cannot get it to run and struggle with a quite simple problem.

What I'm trying to do is set up a simple Sinatra server for accepting requests. On request it checks if a file is present, and if it is not, it queues its creation and responds with an intermediate file.

I have put my configuration into `shoryuken.yml`.

Running `bundle exec shoryuken --config shoryuken.yml --require ./models/worker.rb --pidfile tmp/shoryuken.pid` succeeds and spawns two workers.

When trying to use `Worker.perform_async(params: params)` from my Sinatra-initiated request, however, I get an error saying `Aws::Errors::MissingRegionError - missing region; use :region option or export region name to ENV['AWS_REGION']:`.

This appears reasonable, as this process doesn't know anything about `shoryuken.yml`, as far as I can tell.

What would be a good way to read this file and pass it to Shoryuken? Am I missing something? Read through all wiki pages, but couldn't figure it out.

Thanks!

**Comment by phstc** [comment]
It's because you need to config AWS in your Sinatra app as it's running out of the Shoryuken process.


A possible solution would be to export `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION` as ENV variables. So your aws-sdk will auto pickup these config. If you do that, you don't even need to set these config in the `shoryuken.yml`.

Other option would be to read the `shoryuken.yml` in your Sinatra app and configure the aws-sdk similar to [initialize_aws](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L46). Have a look at https://github.com/phstc/shoryuken/issues/4#issuecomment-77634793 @renanmzmendes has some thoughts on that.

**Comment by janpapenbrock** [comment]
Thank you.

Largely based on @renanmzmendes work I put together a loader living in `lib/shoryuken/loader.rb` for my app, with Shoryuken configuration living in `config/shoryuken.yml`.

```
require 'shoryuken'

def parse_config(config_file)
  if File.exist?(config_file)
    YAML.load(ERB.new(IO.read(config_file)).result)
  else
    raise ArgumentError, "Config file #{config_file} does not exist"
  end
end

config_file = File.join(File.dirname(__FILE__), '..', '..', 'config', 'shoryuken.yml')

config = parse_config(config_file).deep_symbolize_keys
Shoryuken::EnvironmentLoader.load config
```

**Comment by renanmzmendes** [comment]
I'm currently working on a patch for that: an initializer generator (in order to load the environment) for the current rails process. I don't know if the directory structure would be the same though.
